name: phone_monitor
description: Device monitoring application that provides a user with basic information about software and hardware. 

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.2+13

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  battery_info: ^1.0.8
  cpu_reader: ^3.0.0
  device_apps: ^2.1.1
  device_info: ^2.0.2
  disk_space: ^0.1.1
  flutter_launcher_icons: ^0.9.2
  flutter_svg: ^0.22.0
  get: ^4.3.8
  get_storage: ^2.0.3
  launch_review: ^3.0.1
  package_info: ^2.0.2
  settings_ui: ^1.0.0
  system_info: ^1.0.1
  mp_chart:
    git: https://github.com/igrik12/MPFlutterChart

  cupertino_icons: ^1.0.3
  google_mobile_ads: ^0.13.4
  purchases_flutter: ^3.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/phone_monitor.png"

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
